blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/laravel-cacheable?tab=readme-ov-file#laravel-cacheable
    about: Check the documentation for guides and examples.